include $(shell git rev-parse --show-toplevel)/include.mk

# init:
# 	rm go.mod go.sum

#   go mod init github.com/hkloudou/g/gapi
  
#   go get github.com/gin-gonic/gin	github.com/gin-contrib/cors
    # github.com/gin-gonic/gin v1.10.0
    # github.com/go-playground/locales v0.14.1
    # github.com/go-playground/universal-translator v0.18.1
    # github.com/go-playground/validator/v10 v10.22.1